# Generated by Django 5.2.6 on 2025-10-14 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='surat/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_surats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('tujuan', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('tanggal_kegiatan', models.DateField()),
                ('catatan_kunjungan', models.TextField(blank=True, null=True)),
                ('foto_kegiatan', models.ImageField(blank=True, null=True, upload_to='foto_kunjungan')),
                ('foto_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('foto_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('foto_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to=settings.AUTH_USER_MODEL)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to='kunjunganKerja.surat')),
            ],
        ),
    ]
