# Generated by Django 5.2.6 on 2025-11-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunjunganKerja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunjungan',
            old_name='foto_kegiatan',
            new_name='foto_kunjungan',
        ),
        migrations.RenameField(
            model_name='kunjungan',
            old_name='tanggal_kegiatan',
            new_name='tanggal_kunjungan',
        ),
    ]
