# Generated by Django 5.2.6 on 2025-11-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunjunganKerja', '0002_rename_foto_kegiatan_kunjungan_foto_kunjungan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunjungan',
            name='foto_lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='kunjungan',
            name='foto_lon',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
