# Generated by Django 5.2.6 on 2025-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jabatan',
            field=models.CharField(default='asu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nama',
            field=models.CharField(default='asu', max_length=255),
            preserve_default=False,
        ),
    ]
