# Generated by Django 5.2.6 on 2025-09-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=100)),
                ('agenda', models.TextField()),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instansi', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('provinsi', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('keperluan', models.TextField()),
                ('tanggal_kunjungan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
