# Generated by Django 5.2.6 on 2025-10-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pegawai',
            new_name='Pengurus',
        ),
    ]
