# Generated by Django 5.2.6 on 2025-10-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_rename_pegawai_pengurus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengurus',
        ),
    ]
