# Generated by Django 5.2.6 on 2025-10-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=100)),
                ('agenda', models.TextField()),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
